In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
df=pd.read_csv("housing.csv")

In [39]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

1. longitude: A measure of how far west a house is; a higher value is farther west
2. latitude: A measure of how far north a house is; a higher value is farther north
3. housingMedianAge: Median age of a house within a block; a lower number is a newer building
4. totalRooms: Total number of rooms within a block
5. totalBedrooms: Total number of bedrooms within a block
6. population: Total number of people residing within a block
7. households: Total number of households, a group of people residing within a home unit, for a block
8. medianIncome: Median income for households within a block of houses (measured in tens of thousands of US Dollars)
9. medianHouseValue: Median house value for households within a block (measured in US Dollars)
10. oceanProximity: Location of the house w.r.t ocean/sea

In [40]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [41]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [42]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [43]:
df["total_bedrooms"]=df["total_bedrooms"].fillna(df["total_bedrooms"].median())

In [44]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [45]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [46]:
encoded_data=encoder.fit_transform(df[['ocean_proximity']])

In [47]:
encoded_data=encoded_data.toarray()

In [48]:
df_encoder=pd.DataFrame(
    encoded_data,
    columns=encoder.get_feature_names_out(['ocean_proximity'])
)

In [49]:
df_encoder

,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...
20635,0.0,1.0,0.0,0.0,0.0
20636,0.0,1.0,0.0,0.0,0.0
20637,0.0,1.0,0.0,0.0,0.0
20638,0.0,1.0,0.0,0.0,0.0
20639,0.0,1.0,0.0,0.0,0.0

In [50]:
df=pd.concat([df,df_encoder],axis=1)

In [51]:
df.drop('ocean_proximity',axis=1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0.0,1.0,0.0,0.0,0.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0.0,1.0,0.0,0.0,0.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0.0,1.0,0.0,0.0,0.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0.0,1.0,0.0,0.0,0.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0.0,1.0,0.0,0.0,0.0

In [52]:
#df_encoder.reset_index(drop=True,inplace=True)
#df.reset_index(drop=True,inplace=True)

In [53]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,0.0,0.0,0.0,1.0,0.0

In [54]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [55]:
X=df.drop("median_house_value",axis=1)
y=df["median_house_value"]

In [60]:
X.drop("ocean_proximity",axis=1,inplace=True)

In [61]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [62]:
X_scaled=scaler.fit_transform(X)

In [63]:
X_scaled

array([[-1.32783522,  1.05254828,  0.98214266, ..., -0.01556621,
         2.83074203, -0.38446649],
       [-1.32284391,  1.04318455, -0.60701891, ..., -0.01556621,
         2.83074203, -0.38446649],
       [-1.33282653,  1.03850269,  1.85618152, ..., -0.01556621,
         2.83074203, -0.38446649],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.01556621,
        -0.35326426, -0.38446649],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.01556621,
        -0.35326426, -0.38446649],
       [-0.83369581,  1.75014627, -1.00430931, ..., -0.01556621,
        -0.35326426, -0.38446649]], shape=(20640, 13))

In [64]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)

In [65]:
X_train

array([[ 1.26764451, -1.36797628,  0.34647803, ..., -0.01556621,
        -0.35326426,  2.60100692],
       [ 0.7036268 , -0.87169852,  1.61780729, ..., -0.01556621,
        -0.35326426,  2.60100692],
       [-0.45435647, -0.45501247, -1.95780625, ..., -0.01556621,
        -0.35326426,  2.60100692],
       ...,
       [ 0.59381804, -0.74997001,  0.58485227, ..., -0.01556621,
        -0.35326426, -0.38446649],
       [-1.19306993,  0.91209231, -1.08376738, ..., -0.01556621,
        -0.35326426, -0.38446649],
       [-1.42267006,  1.00104776,  1.85618152, ..., -0.01556621,
         2.83074203, -0.38446649]], shape=(16512, 13))

In [66]:
y_train

14196    103000.0
8267     382100.0
17445    172600.0
14265     93400.0
2271      96500.0
           ...
11284    229200.0
11964     97800.0
5390     222100.0
860      283500.0
15795    325000.0
Name: median_house_value, Length: 16512, dtype: float64

In [67]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [68]:
lr.fit(X_train,y_train)

LinearRegression()

In [69]:
y_pred=lr.predict(X_test)

In [71]:
from sklearn.metrics import r2_score,mean_absolute_error
print("R2 score",r2_score(y_test,y_pred))
print("mean absolute error",mean_absolute_error(y_test,y_pred))

R2 score 0.6254240620553606
mean absolute error 50670.73824097192

In [72]:
from sklearn.tree import DecisionTreeRegressor
decisiontree=DecisionTreeRegressor()

In [73]:
decisiontree.fit(X_train,y_train)

DecisionTreeRegressor()

In [74]:
y_predict=decisiontree.predict(X_test)

In [77]:
print("R2_score is:",r2_score(y_test,y_predict))

R2_score is: 0.6322380772250003

In [78]:
from sklearn.ensemble import RandomForestRegressor
Rf=RandomForestRegressor()

In [79]:
Rf.fit(X_train,y_train)

RandomForestRegressor()

In [80]:
y_pred=Rf.predict(X_test)

In [81]:
print("R2 score is:",r2_score(y_test,y_pred))

R2 score is: 0.8157873332734156

In [82]:
Rf=RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

In [83]:
Rf.fit(X_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=42)

In [84]:
y_pred=Rf.predict(X_test)

In [85]:
print("r2 score:",r2_score(y_test,y_pred))

r2 score: 0.7812733539488455

In [86]:
import pickle 
pickle.dump(Rf,open("randomforest.pkl","wb"))

In [87]:
pickle.dump(scaler,open("scaler.pkl","wb"))